#if !defined(AFX_CWANNOTATIONS_H__3D590D54_FF00_41A8_82E1_18E6D05F37D5__INCLUDED_)
#define AFX_CWANNOTATIONS_H__3D590D54_FF00_41A8_82E1_18E6D05F37D5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCWAnnotation;

/////////////////////////////////////////////////////////////////////////////
// CCWAnnotations wrapper class

class CCWAnnotations : public COleDispatchDriver
{
public:
	CCWAnnotations() {}		// Calls COleDispatchDriver default constructor
	CCWAnnotations(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWAnnotations(const CCWAnnotations& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	CCWAnnotation Item(const VARIANT& Item);
	LPUNKNOWN _NewEnum();
	void Remove(const VARIANT& Element);
	void RemoveAll();
	CCWAnnotation Add();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWANNOTATIONS_H__3D590D54_FF00_41A8_82E1_18E6D05F37D5__INCLUDED_)
