#if !defined(AFX_CWANNOTATION_H__0014043F_2E79_4888_B34B_EFE5BED6E7A2__INCLUDED_)
#define AFX_CWANNOTATION_H__0014043F_2E79_4888_B34B_EFE5BED6E7A2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCWPlot;
class CCWShape;

/////////////////////////////////////////////////////////////////////////////
// CCWAnnotation wrapper class

class CCWAnnotation : public COleDispatchDriver
{
public:
	CCWAnnotation() {}		// Calls COleDispatchDriver default constructor
	CCWAnnotation(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWAnnotation(const CCWAnnotation& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	BOOL GetVisible();
	void SetVisible(BOOL);
	long GetCoordinateType();
	void SetCoordinateType(long);
	CCWPlot GetPlot();
	void SetPlot(LPDISPATCH);
	long GetPointIndex();
	void SetPointIndex(long);
	long GetSnapMode();
	void SetSnapMode(long);
	LPDISPATCH GetCaption();
	void SetCaption(LPDISPATCH);
	CCWShape GetShape();
	void SetShape(LPDISPATCH);
	LPDISPATCH GetArrow();
	void SetArrow(LPDISPATCH);
	CString GetName();
	void SetName(LPCTSTR);

// Operations
public:
	void SetBuiltinStyle(long Style);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWANNOTATION_H__0014043F_2E79_4888_B34B_EFE5BED6E7A2__INCLUDED_)
