// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCWTicks;
class CCWLabels;
class CCWValuePairs;

/////////////////////////////////////////////////////////////////////////////
// CCWAxis wrapper class

class CCWAxis : public COleDispatchDriver
{
public:
	CCWAxis() {}		// Calls COleDispatchDriver default constructor
	CCWAxis(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWAxis(const CCWAxis& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetLog();
	void SetLog(BOOL);
	VARIANT GetMaximum();
	void SetMaximum(const VARIANT&);
	VARIANT GetMinimum();
	void SetMinimum(const VARIANT&);
	BOOL GetInverted();
	void SetInverted(BOOL);
	BOOL GetDiscrete();
	void SetDiscrete(BOOL);
	VARIANT GetDiscreteInterval();
	void SetDiscreteInterval(const VARIANT&);
	VARIANT GetDiscreteBase();
	void SetDiscreteBase(const VARIANT&);
	CString GetName();
	void SetName(LPCTSTR);
	BOOL GetAutoScale();
	void SetAutoScale(BOOL);
	CCWTicks GetTicks();
	void SetTicks(LPDISPATCH);
	CString GetFormatString();
	void SetFormatString(LPCTSTR);
	CCWLabels GetLabels();
	void SetLabels(LPDISPATCH);
	BOOL GetVisible();
	void SetVisible(BOOL);
	unsigned long GetCaptionColor();
	void SetCaptionColor(unsigned long);
	BOOL GetValuePairsOnly();
	void SetValuePairsOnly(BOOL);
	CString GetCaption();
	void SetCaption(LPCTSTR);

// Operations
public:
	void SetMinMax(const VARIANT& Minimum, const VARIANT& Maximum);
	CCWValuePairs GetValuePairs();
	void AutoScaleNow();
};
