#if !defined(AFX_CWAXES3D_H__D1FA5A3E_2D05_4388_AF14_57681B9F6506__INCLUDED_)
#define AFX_CWAXES3D_H__D1FA5A3E_2D05_4388_AF14_57681B9F6506__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCWAxis3D;

/////////////////////////////////////////////////////////////////////////////
// CCWAxes3D wrapper class

class CCWAxes3D : public COleDispatchDriver
{
public:
	CCWAxes3D() {}		// Calls COleDispatchDriver default constructor
	CCWAxes3D(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWAxes3D(const CCWAxes3D& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	CCWAxis3D Item(const VARIANT& Item);
	LPUNKNOWN _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWAXES3D_H__D1FA5A3E_2D05_4388_AF14_57681B9F6506__INCLUDED_)
