#if !defined(AFX_CWAXIS3D_H__2CE55B4C_E8C1_41B0_8A3B_1F8206BD765F__INCLUDED_)
#define AFX_CWAXIS3D_H__2CE55B4C_E8C1_41B0_8A3B_1F8206BD765F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCWTicks3D;
class CCWLabels3D;
class CFontDisp;
class CCWValuePairs;

/////////////////////////////////////////////////////////////////////////////
// CCWAxis3D wrapper class

class CCWAxis3D : public COleDispatchDriver
{
public:
	CCWAxis3D() {}		// Calls COleDispatchDriver default constructor
	CCWAxis3D(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWAxis3D(const CCWAxis3D& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetLog();
	void SetLog(BOOL);
	VARIANT GetMaximum();
	void SetMaximum(const VARIANT&);
	VARIANT GetMinimum();
	void SetMinimum(const VARIANT&);
	BOOL GetInverted();
	void SetInverted(BOOL);
	CString GetName();
	void SetName(LPCTSTR);
	BOOL GetAutoScale();
	void SetAutoScale(BOOL);
	CCWTicks3D GetTicks();
	void SetTicks(LPDISPATCH);
	CString GetFormatString();
	void SetFormatString(LPCTSTR);
	CCWLabels3D GetLabels();
	void SetLabels(LPDISPATCH);
	BOOL GetVisible();
	void SetVisible(BOOL);
	CString GetCaption();
	void SetCaption(LPCTSTR);
	unsigned long GetCaptionColor();
	void SetCaptionColor(unsigned long);
	BOOL GetCaptionNormal();
	void SetCaptionNormal(BOOL);
	BOOL GetCaptionOpposite();
	void SetCaptionOpposite(BOOL);
	CFontDisp GetCaptionFont();
	void SetCaptionFont(LPDISPATCH);
	long GetCaptionOrientationStyle();
	void SetCaptionOrientationStyle(long);

// Operations
public:
	void SetMinMax(const VARIANT& Minimum, const VARIANT& Maximum);
	CCWValuePairs GetValuePairs();
	void AutoScaleNow();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWAXIS3D_H__2CE55B4C_E8C1_41B0_8A3B_1F8206BD765F__INCLUDED_)
