#if !defined(AFX_CWAXES_H__7AB98E9B_B396_4340_9B38_5E06B3452BDA__INCLUDED_)
#define AFX_CWAXES_H__7AB98E9B_B396_4340_9B38_5E06B3452BDA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCWAxes wrapper class

class CCWAxes : public COleDispatchDriver
{
public:
	CCWAxes() {}		// Calls COleDispatchDriver default constructor
	CCWAxes(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWAxes(const CCWAxes& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	LPDISPATCH Item(const VARIANT& Item);
	LPUNKNOWN _NewEnum();
	void Remove(const VARIANT& Element);
	void RemoveAll();
	LPDISPATCH Add();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWAXES_H__7AB98E9B_B396_4340_9B38_5E06B3452BDA__INCLUDED_)
