// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cwaxes3d.h"

// Dispatch interfaces referenced by this interface
#include "CWAxis3D.h"


/////////////////////////////////////////////////////////////////////////////
// CCWAxes3D properties

short CCWAxes3D::GetCount()
{
	short result;
	GetProperty(0x100, VT_I2, (void*)&result);
	return result;
}

void CCWAxes3D::SetCount(short propVal)
{
	SetProperty(0x100, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCWAxes3D operations

CCWAxis3D CCWAxes3D::Item(const VARIANT& Item)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&Item);
	return CCWAxis3D(pDispatch);
}

LPUNKNOWN CCWAxes3D::_NewEnum()
{
	LPUNKNOWN result;
	InvokeHelper(0xfffffffc, DISPATCH_METHOD, VT_UNKNOWN, (void*)&result, NULL);
	return result;
}
