// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCWBinding wrapper class

class CCWBinding : public COleDispatchDriver
{
public:
	CCWBinding() {}		// Calls COleDispatchDriver default constructor
	CCWBinding(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWBinding(const CCWBinding& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetBindProperty();
	void SetBindProperty(LPCTSTR);
	CString GetUrl();
	void SetUrl(LPCTSTR);
	long GetAccessMode();
	void SetAccessMode(long);
	CString GetActualURL();
	void SetActualURL(LPCTSTR);
	long GetStatus();
	void SetStatus(long);
	BOOL GetDataUpdated();
	void SetDataUpdated(BOOL);
	long GetLastError();
	void SetLastError(long);
	BOOL GetStatusUpdated();
	void SetStatusUpdated(BOOL);
	BOOL GetAutoConnect();
	void SetAutoConnect(BOOL);
	CString GetLastMessage();
	void SetLastMessage(LPCTSTR);
	long GetTimerInterval();
	void SetTimerInterval(long);
	BOOL GetDataUpdatedEnabled();
	void SetDataUpdatedEnabled(BOOL);
	CString GetName();
	void SetName(LPCTSTR);

// Operations
public:
	void SetBindObject(LPDISPATCH pDisp);
	void Connect();
	void Update();
	void ConnectTo(LPCTSTR URL, long AccessMode);
	void Disconnect();
	BOOL SelectURL(const VARIANT& startURL, const VARIANT& Title, const VARIANT& Options, const VARIANT& Filters);
};
