#if !defined(AFX_CWCONTOUR_H__79621DB1_3A28_411E_AC35_059CDAEDFD64__INCLUDED_)
#define AFX_CWCONTOUR_H__79621DB1_3A28_411E_AC35_059CDAEDFD64__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CFontDisp;

/////////////////////////////////////////////////////////////////////////////
// CCWContour wrapper class

class CCWContour : public COleDispatchDriver
{
public:
	CCWContour() {}		// Calls COleDispatchDriver default constructor
	CCWContour(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWContour(const CCWContour& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	double GetLevel();
	void SetLevel(double);
	unsigned long GetLineColor();
	void SetLineColor(unsigned long);
	long GetLineStyle();
	void SetLineStyle(long);
	double GetLineWidth();
	void SetLineWidth(double);
	CString GetLabelFormat();
	void SetLabelFormat(LPCTSTR);
	unsigned long GetLabelColor();
	void SetLabelColor(unsigned long);
	CFontDisp GetLabelFont();
	void SetLabelFont(LPDISPATCH);
	BOOL GetLabelVisible();
	void SetLabelVisible(BOOL);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWCONTOUR_H__79621DB1_3A28_411E_AC35_059CDAEDFD64__INCLUDED_)
