#if !defined(AFX_CWCONTOURS_H__FC88295E_399A_41A5_AC65_46711AA24B16__INCLUDED_)
#define AFX_CWCONTOURS_H__FC88295E_399A_41A5_AC65_46711AA24B16__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCWContour;

/////////////////////////////////////////////////////////////////////////////
// CCWContours wrapper class

class CCWContours : public COleDispatchDriver
{
public:
	CCWContours() {}		// Calls COleDispatchDriver default constructor
	CCWContours(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWContours(const CCWContours& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);
	BOOL GetAnchorEnabled();
	void SetAnchorEnabled(BOOL);
	double GetAnchor();
	void SetAnchor(double);
	long GetBasis();
	void SetBasis(long);
	double GetInterval();
	void SetInterval(double);
	VARIANT GetLevelList();
	void SetLevelList(const VARIANT&);
	long GetLevels();
	void SetLevels(long);
	long GetLabelOrientationStyle();
	void SetLabelOrientationStyle(long);

// Operations
public:
	CCWContour Item(const VARIANT& Item);
	LPUNKNOWN _NewEnum();
	void Remove(const VARIANT& Element);
	void RemoveAll();
	void SetLineColor(unsigned long LineColor);
	void SetLineStyle(long LineStyle);
	void SetLineWidth(double LineWidth);
	void SetLabelFormat(LPCTSTR Label);
	void SetLabelColor(unsigned long LabelColor);
	void SetLabelFont(LPDISPATCH LabelFont);
	void SetLabelVisible(BOOL LabelVisible);
	void Add(double Level);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWCONTOURS_H__FC88295E_399A_41A5_AC65_46711AA24B16__INCLUDED_)
