#if !defined(AFX_CWCURSOR3D_H__310B6775_6C6E_4EE9_97B6_33A8F457DFBA__INCLUDED_)
#define AFX_CWCURSOR3D_H__310B6775_6C6E_4EE9_97B6_33A8F457DFBA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCWPlot3D;
class CFontDisp;

/////////////////////////////////////////////////////////////////////////////
// CCWCursor3D wrapper class

class CCWCursor3D : public COleDispatchDriver
{
public:
	CCWCursor3D() {}		// Calls COleDispatchDriver default constructor
	CCWCursor3D(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWCursor3D(const CCWCursor3D& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	CString GetName();
	void SetName(LPCTSTR);
	BOOL GetVisible();
	void SetVisible(BOOL);
	double GetXPosition();
	void SetXPosition(double);
	double GetYPosition();
	void SetYPosition(double);
	double GetZPosition();
	void SetZPosition(double);
	CCWPlot3D GetPlot();
	void SetPlot(LPDISPATCH);
	long GetRow();
	void SetRow(long);
	long GetColumn();
	void SetColumn(long);
	BOOL GetNameVisible();
	void SetNameVisible(BOOL);
	BOOL GetPositionVisible();
	void SetPositionVisible(BOOL);
	BOOL GetXYPlaneVisible();
	void SetXYPlaneVisible(BOOL);
	BOOL GetXZPlaneVisible();
	void SetXZPlaneVisible(BOOL);
	BOOL GetYZPlaneVisible();
	void SetYZPlaneVisible(BOOL);
	long GetTextBackgroundTransparency();
	void SetTextBackgroundTransparency(long);
	unsigned long GetPointColor();
	void SetPointColor(unsigned long);
	unsigned long GetLineColor();
	void SetLineColor(unsigned long);
	unsigned long GetTextColor();
	void SetTextColor(unsigned long);
	unsigned long GetTextBackColor();
	void SetTextBackColor(unsigned long);
	unsigned long GetPlaneColor();
	void SetPlaneColor(unsigned long);
	double GetPointSize();
	void SetPointSize(double);
	double GetLineWidth();
	void SetLineWidth(double);
	long GetPlaneTransparency();
	void SetPlaneTransparency(long);
	long GetPointStyle();
	void SetPointStyle(long);
	long GetLineStyle();
	void SetLineStyle(long);
	long GetSnapMode();
	void SetSnapMode(long);
	CFontDisp GetFont();
	void SetFont(LPDISPATCH);

// Operations
public:
	void SetPosition(double X, double Y, double Z);
	void SetColor(unsigned long Color);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWCURSOR3D_H__310B6775_6C6E_4EE9_97B6_33A8F457DFBA__INCLUDED_)
