// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPictureDisp;

/////////////////////////////////////////////////////////////////////////////
// CCWImage wrapper class

class CCWImage : public COleDispatchDriver
{
public:
	CCWImage() {}		// Calls COleDispatchDriver default constructor
	CCWImage(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWImage(const CCWImage& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetUrl();
	void SetUrl(LPCTSTR);
	CPictureDisp GetPicture();
	void SetPicture(LPDISPATCH);
	BOOL GetSaveLink();
	void SetSaveLink(BOOL);
	BOOL GetStretch();
	void SetStretch(BOOL);
	BOOL GetTile();
	void SetTile(BOOL);
	BOOL GetTransparent();
	void SetTransparent(BOOL);
	unsigned long GetTransparentColor();
	void SetTransparentColor(unsigned long);
	BOOL GetVisible();
	void SetVisible(BOOL);
	long GetBlinkInterval();
	void SetBlinkInterval(long);
	long GetAnimateInterval();
	void SetAnimateInterval(long);
	BOOL GetReverseAnimation();
	void SetReverseAnimation(BOOL);
	long GetAnimateRows();
	void SetAnimateRows(long);
	long GetAnimateColumns();
	void SetAnimateColumns(long);
	unsigned long GetColor();
	void SetColor(unsigned long);
	BOOL GetSubstitute();
	void SetSubstitute(BOOL);
	BOOL GetFlipH();
	void SetFlipH(BOOL);
	BOOL GetFlipV();
	void SetFlipV(BOOL);
	long GetTolerance();
	void SetTolerance(long);
	unsigned long GetSubstituteColor();
	void SetSubstituteColor(unsigned long);

// Operations
public:
	void Reload();
};
