#if !defined(AFX_CWLABELS3D_H__6007F9E5_2821_4930_9878_D1082CAFE46A__INCLUDED_)
#define AFX_CWLABELS3D_H__6007F9E5_2821_4930_9878_D1082CAFE46A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CFontDisp;

/////////////////////////////////////////////////////////////////////////////
// CCWLabels3D wrapper class

class CCWLabels3D : public COleDispatchDriver
{
public:
	CCWLabels3D() {}		// Calls COleDispatchDriver default constructor
	CCWLabels3D(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWLabels3D(const CCWLabels3D& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetNormal();
	void SetNormal(BOOL);
	BOOL GetOpposite();
	void SetOpposite(BOOL);
	unsigned long GetColor();
	void SetColor(unsigned long);
	CFontDisp GetFont();
	void SetFont(LPDISPATCH);
	long GetOrientationStyle();
	void SetOrientationStyle(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWLABELS3D_H__6007F9E5_2821_4930_9878_D1082CAFE46A__INCLUDED_)
