// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cwlabels.h"


/////////////////////////////////////////////////////////////////////////////
// CCWLabels properties

BOOL CCWLabels::GetAbove()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CCWLabels::SetAbove(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

BOOL CCWLabels::GetBelow()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CCWLabels::SetBelow(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CCWLabels::GetLeft()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CCWLabels::SetLeft(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CCWLabels::GetRight()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CCWLabels::SetRight(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

unsigned long CCWLabels::GetColor()
{
	unsigned long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CCWLabels::SetColor(unsigned long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

BOOL CCWLabels::GetRadial()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CCWLabels::SetRadial(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

long CCWLabels::GetWidth()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CCWLabels::SetWidth(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCWLabels operations
