// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cwlabels3d.h"

// Dispatch interfaces referenced by this interface
#include "fontdisp.h"


/////////////////////////////////////////////////////////////////////////////
// CCWLabels3D properties

BOOL CCWLabels3D::GetNormal()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CCWLabels3D::SetNormal(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

BOOL CCWLabels3D::GetOpposite()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CCWLabels3D::SetOpposite(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

unsigned long CCWLabels3D::GetColor()
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CCWLabels3D::SetColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

CFontDisp CCWLabels3D::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x4, VT_DISPATCH, (void*)&pDispatch);
	return CFontDisp(pDispatch);
}

void CCWLabels3D::SetFont(LPDISPATCH propVal)
{
	SetProperty(0x4, VT_DISPATCH, propVal);
}

long CCWLabels3D::GetOrientationStyle()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CCWLabels3D::SetOrientationStyle(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCWLabels3D operations
