// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cwlight.h"


/////////////////////////////////////////////////////////////////////////////
// CCWLight properties

BOOL CCWLight::GetEnabled()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CCWLight::SetEnabled(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

long CCWLight::GetAttenuation()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CCWLight::SetAttenuation(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

double CCWLight::GetLatitude()
{
	double result;
	GetProperty(0x3, VT_R8, (void*)&result);
	return result;
}

void CCWLight::SetLatitude(double propVal)
{
	SetProperty(0x3, VT_R8, propVal);
}

double CCWLight::GetLongitude()
{
	double result;
	GetProperty(0x4, VT_R8, (void*)&result);
	return result;
}

void CCWLight::SetLongitude(double propVal)
{
	SetProperty(0x4, VT_R8, propVal);
}

double CCWLight::GetDistance()
{
	double result;
	GetProperty(0x5, VT_R8, (void*)&result);
	return result;
}

void CCWLight::SetDistance(double propVal)
{
	SetProperty(0x5, VT_R8, propVal);
}

unsigned long CCWLight::GetColor()
{
	unsigned long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CCWLight::SetColor(unsigned long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCWLight operations
