// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cwlights.h"

// Dispatch interfaces referenced by this interface
#include "cwlight.h"


/////////////////////////////////////////////////////////////////////////////
// CCWLights properties

short CCWLights::GetCount()
{
	short result;
	GetProperty(0x100, VT_I2, (void*)&result);
	return result;
}

void CCWLights::SetCount(short propVal)
{
	SetProperty(0x100, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCWLights operations

CCWLight CCWLights::Item(const VARIANT& Item)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&Item);
	return CCWLight(pDispatch);
}

LPUNKNOWN CCWLights::_NewEnum()
{
	LPUNKNOWN result;
	InvokeHelper(0xfffffffc, DISPATCH_METHOD, VT_UNKNOWN, (void*)&result, NULL);
	return result;
}
