#if !defined(AFX_CWLIGHT_H__C594BC2E_BF91_447F_B1EB_17DFCB4945A7__INCLUDED_)
#define AFX_CWLIGHT_H__C594BC2E_BF91_447F_B1EB_17DFCB4945A7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCWLight wrapper class

class CCWLight : public COleDispatchDriver
{
public:
	CCWLight() {}		// Calls COleDispatchDriver default constructor
	CCWLight(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWLight(const CCWLight& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	long GetAttenuation();
	void SetAttenuation(long);
	double GetLatitude();
	void SetLatitude(double);
	double GetLongitude();
	void SetLongitude(double);
	double GetDistance();
	void SetDistance(double);
	unsigned long GetColor();
	void SetColor(unsigned long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWLIGHT_H__C594BC2E_BF91_447F_B1EB_17DFCB4945A7__INCLUDED_)
