#if !defined(AFX_CWLIGHTS_H__0BE10A7C_5015_4F57_A4E1_5FD35B4307EF__INCLUDED_)
#define AFX_CWLIGHTS_H__0BE10A7C_5015_4F57_A4E1_5FD35B4307EF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCWLight;

/////////////////////////////////////////////////////////////////////////////
// CCWLights wrapper class

class CCWLights : public COleDispatchDriver
{
public:
	CCWLights() {}		// Calls COleDispatchDriver default constructor
	CCWLights(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWLights(const CCWLights& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	CCWLight Item(const VARIANT& Item);
	LPUNKNOWN _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWLIGHTS_H__0BE10A7C_5015_4F57_A4E1_5FD35B4307EF__INCLUDED_)
