// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cwpicturedisp.h"

// Dispatch interfaces referenced by this interface
#include "cwimage.h"


/////////////////////////////////////////////////////////////////////////////
// CCWPictureDisp properties

CCWImage CCWPictureDisp::GetCWImage()
{
	LPDISPATCH pDispatch;
	GetProperty(0x100, VT_DISPATCH, (void*)&pDispatch);
	return CCWImage(pDispatch);
}

void CCWPictureDisp::SetCWImage(LPDISPATCH propVal)
{
	SetProperty(0x100, VT_DISPATCH, propVal);
}

long CCWPictureDisp::GetHandle()
{
	long result;
	GetProperty(0x0, VT_I4, (void*)&result);
	return result;
}

void CCWPictureDisp::SetHandle(long propVal)
{
	SetProperty(0x0, VT_I4, propVal);
}

long CCWPictureDisp::GetHPal()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CCWPictureDisp::SetHPal(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

short CCWPictureDisp::GetType()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CCWPictureDisp::SetType(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

long CCWPictureDisp::GetWidth()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CCWPictureDisp::SetWidth(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

long CCWPictureDisp::GetHeight()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CCWPictureDisp::SetHeight(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCWPictureDisp operations
