#if !defined(AFX_CWPLOT3D_H__EB213CBC_268B_4A6D_86C4_51F9BA38C3CB__INCLUDED_)
#define AFX_CWPLOT3D_H__EB213CBC_268B_4A6D_86C4_51F9BA38C3CB__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCWContours;
class CCWAxis3D;

/////////////////////////////////////////////////////////////////////////////
// CCWPlot3D wrapper class

class CCWPlot3D : public COleDispatchDriver
{
public:
	CCWPlot3D() {}		// Calls COleDispatchDriver default constructor
	CCWPlot3D(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWPlot3D(const CCWPlot3D& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	CString GetName();
	void SetName(LPCTSTR);
	BOOL GetVisible();
	void SetVisible(BOOL);
	BOOL GetMultiPlot();
	void SetMultiPlot(BOOL);
	BOOL GetAutoScale();
	void SetAutoScale(BOOL);
	long GetStyle();
	void SetStyle(long);
	long GetFillStyle();
	void SetFillStyle(long);
	unsigned long GetFillColor();
	void SetFillColor(unsigned long);
	long GetLineStyle();
	void SetLineStyle(long);
	unsigned long GetLineColor();
	void SetLineColor(unsigned long);
	double GetLineWidth();
	void SetLineWidth(double);
	long GetPointStyle();
	void SetPointStyle(long);
	unsigned long GetPointColor();
	void SetPointColor(unsigned long);
	double GetPointSize();
	void SetPointSize(double);
	long GetPointFrequency();
	void SetPointFrequency(long);
	BOOL GetCacheData();
	void SetCacheData(BOOL);
	long GetColorMapStyle();
	void SetColorMapStyle(long);
	long GetCoordinateSystem();
	void SetCoordinateSystem(long);
	BOOL GetProjectionXY();
	void SetProjectionXY(BOOL);
	BOOL GetProjectionXZ();
	void SetProjectionXZ(BOOL);
	BOOL GetProjectionYZ();
	void SetProjectionYZ(BOOL);
	BOOL GetShowProjectionsOnly();
	void SetShowProjectionsOnly(BOOL);
	long GetTransparency();
	void SetTransparency(long);
	BOOL GetColorMapInterpolate();
	void SetColorMapInterpolate(BOOL);
	BOOL GetColorMapAutoScale();
	void SetColorMapAutoScale(BOOL);
	BOOL GetColorMapLog();
	void SetColorMapLog(BOOL);
	VARIANT GetColorMapValues();
	void SetColorMapValues(const VARIANT&);
	VARIANT GetColorMapColors();
	void SetColorMapColors(const VARIANT&);

// Operations
public:
	void ClearData();
	void Plot3DSimpleSurface(const VARIANT& zMatrix, const VARIANT& wMatrix);
	void Plot3DSurface(const VARIANT& xVector, const VARIANT& yVector, const VARIANT& zMatrix, const VARIANT& wMatrix);
	void Plot3DParametricSurface(const VARIANT& xMatrix, const VARIANT& yMatrix, const VARIANT& zMatrix, const VARIANT& wMatrix);
	void Plot3DCurve(const VARIANT& xVector, const VARIANT& yVector, const VARIANT& zVector, const VARIANT& wVector);
	CCWContours GetContours();
	CCWAxis3D GetXAxis();
	CCWAxis3D GetYAxis();
	CCWAxis3D GetZAxis();
	void Plot3DMesh(const VARIANT& xVector, const VARIANT& yVector, const VARIANT& zVector, const VARIANT& wVector);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWPLOT3D_H__EB213CBC_268B_4A6D_86C4_51F9BA38C3CB__INCLUDED_)
