#if !defined(AFX_CWPLOT_H__24FBB163_72FB_40D8_98C9_84F5F98CE011__INCLUDED_)
#define AFX_CWPLOT_H__24FBB163_72FB_40D8_98C9_84F5F98CE011__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCWPlot wrapper class

class CCWPlot : public COleDispatchDriver
{
public:
	CCWPlot() {}		// Calls COleDispatchDriver default constructor
	CCWPlot(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWPlot(const CCWPlot& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetLineStyle();
	void SetLineStyle(long);
	long GetPointStyle();
	void SetPointStyle(long);
	CString GetName();
	void SetName(LPCTSTR);
	short GetLineWidth();
	void SetLineWidth(short);
	BOOL GetVisible();
	void SetVisible(BOOL);
	LPDISPATCH GetXAxis();
	void SetXAxis(LPDISPATCH);
	BOOL GetFillToBase();
	void SetFillToBase(BOOL);
	BOOL GetLineToBase();
	void SetLineToBase(BOOL);
	VARIANT GetBaseValue();
	void SetBaseValue(const VARIANT&);
	LPDISPATCH GetBasePlot();
	void SetBasePlot(LPDISPATCH);
	BOOL GetMultiPlot();
	void SetMultiPlot(BOOL);
	BOOL GetAutoScale();
	void SetAutoScale(BOOL);
	LPDISPATCH GetYAxis();
	void SetYAxis(LPDISPATCH);
	unsigned long GetLineColor();
	void SetLineColor(unsigned long);
	unsigned long GetPointColor();
	void SetPointColor(unsigned long);
	unsigned long GetFillColor();
	void SetFillColor(unsigned long);
	unsigned long GetLineToBaseColor();
	void SetLineToBaseColor(unsigned long);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	BOOL GetTempPlot();
	void SetTempPlot(BOOL);
	double GetDefaultxInc();
	void SetDefaultxInc(double);
	double GetDefaultxFirst();
	void SetDefaultxFirst(double);
	BOOL GetDefaultPlotPerRow();
	void SetDefaultPlotPerRow(BOOL);
	VARIANT GetYDataAppend();
	void SetYDataAppend(const VARIANT&);
	VARIANT GetXYDataAppend();
	void SetXYDataAppend(const VARIANT&);
	VARIANT GetYData();
	void SetYData(const VARIANT&);
	VARIANT GetXYData();
	void SetXYData(const VARIANT&);

// Operations
public:
	void ClearData();
	void PlotY(const VARIANT& YData, const VARIANT& xFirst, const VARIANT& xInc);
	void PlotXvsY(const VARIANT& xData, const VARIANT& YData);
	void ChartY(const VARIANT& YData, const VARIANT& xInc);
	void ChartXvsY(const VARIANT& xData, const VARIANT& YData);
	void PlotXY(const VARIANT& XYData, const VARIANT& bXInFirstRow);
	void ChartXY(const VARIANT& XYData, const VARIANT& bXInFirstRow);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWPLOT_H__24FBB163_72FB_40D8_98C9_84F5F98CE011__INCLUDED_)
