#if !defined(AFX_CWPLOTS3D_H__B4B53329_015A_407A_AF33_732DFFBDBAC5__INCLUDED_)
#define AFX_CWPLOTS3D_H__B4B53329_015A_407A_AF33_732DFFBDBAC5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCWPlot3D;

/////////////////////////////////////////////////////////////////////////////
// CCWPlots3D wrapper class

class CCWPlots3D : public COleDispatchDriver
{
public:
	CCWPlots3D() {}		// Calls COleDispatchDriver default constructor
	CCWPlots3D(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWPlots3D(const CCWPlots3D& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	CCWPlot3D Item(const VARIANT& Item);
	LPUNKNOWN _NewEnum();
	void Remove(const VARIANT& Element);
	void RemoveAll();
	CCWPlot3D Add();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CWPLOTS3D_H__B4B53329_015A_407A_AF33_732DFFBDBAC5__INCLUDED_)
