// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cwpointer.h"


/////////////////////////////////////////////////////////////////////////////
// CCWPointer properties

VARIANT CCWPointer::GetValue()
{
	VARIANT result;
	GetProperty(0x1, VT_VARIANT, (void*)&result);
	return result;
}

void CCWPointer::SetValue(const VARIANT& propVal)
{
	SetProperty(0x1, VT_VARIANT, &propVal);
}

long CCWPointer::GetFillStyle()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CCWPointer::SetFillStyle(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

CString CCWPointer::GetName()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CCWPointer::SetName(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

unsigned long CCWPointer::GetFillColor()
{
	unsigned long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CCWPointer::SetFillColor(unsigned long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

long CCWPointer::GetIndex()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CCWPointer::SetIndex(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

long CCWPointer::GetStyle()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CCWPointer::SetStyle(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

BOOL CCWPointer::GetVisible()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CCWPointer::SetVisible(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

long CCWPointer::GetMode()
{
	long result;
	GetProperty(0x8, VT_I4, (void*)&result);
	return result;
}

void CCWPointer::SetMode(long propVal)
{
	SetProperty(0x8, VT_I4, propVal);
}

unsigned long CCWPointer::GetColor()
{
	unsigned long result;
	GetProperty(0x9, VT_I4, (void*)&result);
	return result;
}

void CCWPointer::SetColor(unsigned long propVal)
{
	SetProperty(0x9, VT_I4, propVal);
}

long CCWPointer::GetValuePairIndex()
{
	long result;
	GetProperty(0xa, VT_I4, (void*)&result);
	return result;
}

void CCWPointer::SetValuePairIndex(long propVal)
{
	SetProperty(0xa, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCWPointer operations
