// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCWStatistics wrapper class

class CCWStatistics : public COleDispatchDriver
{
public:
	CCWStatistics() {}		// Calls COleDispatchDriver default constructor
	CCWStatistics(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWStatistics(const CCWStatistics& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	VARIANT GetMean();
	void SetMean(const VARIANT&);
	VARIANT GetMaximum();
	void SetMaximum(const VARIANT&);
	VARIANT GetMinimum();
	void SetMinimum(const VARIANT&);

// Operations
public:
	void Reset();
};
