// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cwticks3d.h"


/////////////////////////////////////////////////////////////////////////////
// CCWTicks3D properties

BOOL CCWTicks3D::GetInside()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CCWTicks3D::SetInside(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

BOOL CCWTicks3D::GetOutside()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CCWTicks3D::SetOutside(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CCWTicks3D::GetNormal()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CCWTicks3D::SetNormal(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CCWTicks3D::GetOpposite()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CCWTicks3D::SetOpposite(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

VARIANT CCWTicks3D::GetMajorDivisions()
{
	VARIANT result;
	GetProperty(0x5, VT_VARIANT, (void*)&result);
	return result;
}

void CCWTicks3D::SetMajorDivisions(const VARIANT& propVal)
{
	SetProperty(0x5, VT_VARIANT, &propVal);
}

VARIANT CCWTicks3D::GetMinorDivisions()
{
	VARIANT result;
	GetProperty(0x6, VT_VARIANT, (void*)&result);
	return result;
}

void CCWTicks3D::SetMinorDivisions(const VARIANT& propVal)
{
	SetProperty(0x6, VT_VARIANT, &propVal);
}

BOOL CCWTicks3D::GetAutoDivisions()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CCWTicks3D::SetAutoDivisions(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

VARIANT CCWTicks3D::GetMajorUnitsInterval()
{
	VARIANT result;
	GetProperty(0x8, VT_VARIANT, (void*)&result);
	return result;
}

void CCWTicks3D::SetMajorUnitsInterval(const VARIANT& propVal)
{
	SetProperty(0x8, VT_VARIANT, &propVal);
}

VARIANT CCWTicks3D::GetMajorUnitsBase()
{
	VARIANT result;
	GetProperty(0x9, VT_VARIANT, (void*)&result);
	return result;
}

void CCWTicks3D::SetMajorUnitsBase(const VARIANT& propVal)
{
	SetProperty(0x9, VT_VARIANT, &propVal);
}

VARIANT CCWTicks3D::GetMinorUnitsInterval()
{
	VARIANT result;
	GetProperty(0xa, VT_VARIANT, (void*)&result);
	return result;
}

void CCWTicks3D::SetMinorUnitsInterval(const VARIANT& propVal)
{
	SetProperty(0xa, VT_VARIANT, &propVal);
}

BOOL CCWTicks3D::GetMajorGrid()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

void CCWTicks3D::SetMajorGrid(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

BOOL CCWTicks3D::GetMinorGrid()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CCWTicks3D::SetMinorGrid(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

unsigned long CCWTicks3D::GetMajorGridColor()
{
	unsigned long result;
	GetProperty(0xd, VT_I4, (void*)&result);
	return result;
}

void CCWTicks3D::SetMajorGridColor(unsigned long propVal)
{
	SetProperty(0xd, VT_I4, propVal);
}

unsigned long CCWTicks3D::GetMinorGridColor()
{
	unsigned long result;
	GetProperty(0xe, VT_I4, (void*)&result);
	return result;
}

void CCWTicks3D::SetMinorGridColor(unsigned long propVal)
{
	SetProperty(0xe, VT_I4, propVal);
}

BOOL CCWTicks3D::GetMajorTicks()
{
	BOOL result;
	GetProperty(0xf, VT_BOOL, (void*)&result);
	return result;
}

void CCWTicks3D::SetMajorTicks(BOOL propVal)
{
	SetProperty(0xf, VT_BOOL, propVal);
}

BOOL CCWTicks3D::GetMinorTicks()
{
	BOOL result;
	GetProperty(0x10, VT_BOOL, (void*)&result);
	return result;
}

void CCWTicks3D::SetMinorTicks(BOOL propVal)
{
	SetProperty(0x10, VT_BOOL, propVal);
}

unsigned long CCWTicks3D::GetMajorTickColor()
{
	unsigned long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CCWTicks3D::SetMajorTickColor(unsigned long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

unsigned long CCWTicks3D::GetMinorTickColor()
{
	unsigned long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CCWTicks3D::SetMinorTickColor(unsigned long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCWTicks3D operations
