// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCWTicks wrapper class

class CCWTicks : public COleDispatchDriver
{
public:
	CCWTicks() {}		// Calls COleDispatchDriver default constructor
	CCWTicks(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWTicks(const CCWTicks& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetAbove();
	void SetAbove(BOOL);
	BOOL GetBelow();
	void SetBelow(BOOL);
	BOOL GetLeft();
	void SetLeft(BOOL);
	BOOL GetRight();
	void SetRight(BOOL);
	BOOL GetInside();
	void SetInside(BOOL);
	BOOL GetOutside();
	void SetOutside(BOOL);
	VARIANT GetMajorDivisions();
	void SetMajorDivisions(const VARIANT&);
	VARIANT GetMinorDivisions();
	void SetMinorDivisions(const VARIANT&);
	BOOL GetAutoDivisions();
	void SetAutoDivisions(BOOL);
	VARIANT GetMajorUnitsInterval();
	void SetMajorUnitsInterval(const VARIANT&);
	VARIANT GetMajorUnitsBase();
	void SetMajorUnitsBase(const VARIANT&);
	VARIANT GetMinorUnitsInterval();
	void SetMinorUnitsInterval(const VARIANT&);
	BOOL GetMajorGrid();
	void SetMajorGrid(BOOL);
	BOOL GetMinorGrid();
	void SetMinorGrid(BOOL);
	unsigned long GetMajorGridColor();
	void SetMajorGridColor(unsigned long);
	unsigned long GetMinorGridColor();
	void SetMinorGridColor(unsigned long);
	BOOL GetMajorTicks();
	void SetMajorTicks(BOOL);
	BOOL GetMinorTicks();
	void SetMinorTicks(BOOL);
	unsigned long GetMajorTickColor();
	void SetMajorTickColor(unsigned long);
	unsigned long GetMinorTickColor();
	void SetMinorTickColor(unsigned long);

// Operations
public:
};
