// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCWValuePair wrapper class

class CCWValuePair : public COleDispatchDriver
{
public:
	CCWValuePair() {}		// Calls COleDispatchDriver default constructor
	CCWValuePair(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWValuePair(const CCWValuePair& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetName();
	void SetName(LPCTSTR);
	VARIANT GetValue();
	void SetValue(const VARIANT&);

// Operations
public:
};
