// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCWValuePair;

/////////////////////////////////////////////////////////////////////////////
// CCWValuePairs wrapper class

class CCWValuePairs : public COleDispatchDriver
{
public:
	CCWValuePairs() {}		// Calls COleDispatchDriver default constructor
	CCWValuePairs(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCWValuePairs(const CCWValuePairs& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);
	long GetLabelType();
	void SetLabelType(long);
	long GetLocation();
	void SetLocation(long);
	BOOL GetMajorTicks();
	void SetMajorTicks(BOOL);
	BOOL GetGridLines();
	void SetGridLines(BOOL);

// Operations
public:
	CCWValuePair Item(const VARIANT& Item);
	LPUNKNOWN _NewEnum();
	void Remove(const VARIANT& Element);
	void RemoveAll();
	CCWValuePair Add();
	void Swap(const VARIANT& element1, const VARIANT& element2);
};
